services:
  backend:
    container_name: backend-app
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mogo-db
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis-cache
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo-data:
