name: Continous Validation and Integration
on:
  push:
    branches: [main, staging]
jobs:
  validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Code Linting
        id: lint
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          VALIDATE_JSX_PRETTIER: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_CSS: false
          VALIDATE_ENV: false
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
          DISABLE_ERRORS: true

  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      BACKEND_SERVICE_NAME: backend
      FRONTEND_IMAGE_NAME: frontend
      BACKEND_FOLDER: backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "SHA=$(echo $GITHUB_SHA | cut -c1-6)" >> $GITHUB_OUTPUT

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build backend
        run: docker compose -f backend/docker-comspose.yaml build ${{env.BACKEND_SERVICE_NAME}}
      - name: Tag backend image
        run: |
          docker tag ${{env.BACKEND_FOLDER}}-${{env.BACKEND_SERVICE_NAME}} ${{secrets.DOCKER_USERNAME}}/backend-app:${{steps.sha.outputs.SHA}}
      - name: Push backend image to docker hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/backend-app:${{steps.sha.outputs.SHA}}
